spring:
  application:
    name: basicSampleSite
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@221.132.77.234:1521:DBCA2
    driver-class-name: oracle.jdbc.OracleDriver
    username: mcreact
    password: mcreact1234
    hikari:
      connection-timeout: 30000 # 30초
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000 # 10분
      max-lifetime: 1800000 # 30분
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update  # 테이블이 있는지 확인만 하고 업데이트는 하지 않음
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
logging:
  level:
    com:
      example:
        basicsamplesite: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        jdbc: DEBUG
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/bascicSampleSite.log
