spring:
  application:
    name: basicSampleSite
  profiles:
    active: dev
    include:
      - db
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        jdbc:
          batch_size: 10
          use_sql_comments: true
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect:
          enhanced_id_generators: false
    show-sql: true
logging:
  level:
    com:
      example:
        basicsamplesite: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        jdbc: DEBUG
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/bascicSampleSite.log
